[default_session]
startup_command = "nvim -c ':FzfLua files'"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "l"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "l"

[[session]]
name = "Dotfiles ó°˜“"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "Kitty config î˜•"
path = "~/dotfiles/kitty/.config/kitty"
startup_command = "nvim kitty.conf"

[[session]]
name = "Tmux config î˜•"
path = "~/dotfiles/tmux/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "My binaries"
path = "~/dotfiles/bin/.local/bin"

[[session]]
name = "Neovim config î˜•"
path = "~/.config/nvim"
